-- Create medicinal plants table
CREATE TABLE public.medicinal_plants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  common_name TEXT NOT NULL,
  scientific_name TEXT NOT NULL,
  category TEXT NOT NULL,
  parts_used TEXT[] NOT NULL,
  medicinal_properties TEXT[] NOT NULL,
  common_uses TEXT[] NOT NULL,
  precautions TEXT,
  description TEXT NOT NULL,
  image_keywords TEXT[] NOT NULL, -- Keywords for image matching
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.medicinal_plants ENABLE ROW LEVEL SECURITY;

-- Allow public read access (no authentication needed for viewing plants)
CREATE POLICY "Anyone can view medicinal plants"
ON public.medicinal_plants
FOR SELECT
USING (true);

-- Create index for faster searches
CREATE INDEX idx_medicinal_plants_common_name ON public.medicinal_plants(common_name);
CREATE INDEX idx_medicinal_plants_scientific_name ON public.medicinal_plants(scientific_name);

-- Insert 100 medicinal plants with comprehensive data
INSERT INTO public.medicinal_plants (common_name, scientific_name, category, parts_used, medicinal_properties, common_uses, precautions, description, image_keywords) VALUES
('Holy Basil (Tulsi)', 'Ocimum sanctum', 'Herb', ARRAY['Leaves', 'Seeds'], ARRAY['Antibacterial', 'Antiviral', 'Adaptogenic', 'Anti-inflammatory'], ARRAY['Respiratory infections', 'Stress relief', 'Fever reduction', 'Immune support'], 'May lower blood sugar. Avoid during pregnancy.', 'Sacred plant in Ayurveda with powerful healing properties for respiratory and immune health.', ARRAY['tulsi', 'basil', 'holy basil', 'ocimum']),
('Neem', 'Azadirachta indica', 'Tree', ARRAY['Leaves', 'Bark', 'Seeds', 'Oil'], ARRAY['Antibacterial', 'Antifungal', 'Antiviral', 'Blood purifier'], ARRAY['Skin conditions', 'Dental health', 'Diabetes management', 'Wound healing'], 'Bitter taste. Not for long-term internal use.', 'Versatile medicinal tree known as "village pharmacy" with extensive antimicrobial properties.', ARRAY['neem', 'azadirachta', 'margosa']),
('Aloe Vera', 'Aloe barbadensis', 'Succulent', ARRAY['Gel', 'Latex'], ARRAY['Anti-inflammatory', 'Wound healing', 'Moisturizing', 'Laxative'], ARRAY['Burns', 'Skin care', 'Digestive issues', 'Wound healing'], 'Latex can cause cramping. Avoid during pregnancy.', 'Succulent plant with cooling gel used extensively for skin and digestive health.', ARRAY['aloe', 'aloe vera', 'succulent']),
('Turmeric', 'Curcuma longa', 'Rhizome', ARRAY['Rhizome', 'Root'], ARRAY['Anti-inflammatory', 'Antioxidant', 'Antimicrobial', 'Hepatoprotective'], ARRAY['Inflammation', 'Joint pain', 'Liver health', 'Wound healing'], 'May interact with blood thinners. High doses can cause stomach upset.', 'Golden spice with powerful anti-inflammatory compound curcumin.', ARRAY['turmeric', 'curcuma', 'haldi']),
('Ginger', 'Zingiber officinale', 'Rhizome', ARRAY['Rhizome', 'Root'], ARRAY['Anti-nausea', 'Anti-inflammatory', 'Digestive aid', 'Antimicrobial'], ARRAY['Nausea', 'Motion sickness', 'Digestive issues', 'Cold and flu'], 'May interact with blood thinners. Avoid high doses during pregnancy.', 'Warming spice with digestive and anti-nausea properties.', ARRAY['ginger', 'zingiber', 'rhizome']),
('Ashwagandha', 'Withania somnifera', 'Shrub', ARRAY['Roots', 'Berries'], ARRAY['Adaptogenic', 'Anti-stress', 'Immunomodulatory', 'Neuroprotective'], ARRAY['Stress reduction', 'Anxiety', 'Energy boost', 'Cognitive function'], 'Not for use during pregnancy. May interact with thyroid medications.', 'Powerful adaptogen known as "Indian Ginseng" for stress and vitality.', ARRAY['ashwagandha', 'withania', 'indian ginseng']),
('Brahmi', 'Bacopa monnieri', 'Herb', ARRAY['Whole plant', 'Leaves'], ARRAY['Neuroprotective', 'Memory enhancer', 'Anti-anxiety', 'Antioxidant'], ARRAY['Memory improvement', 'Cognitive function', 'Anxiety', 'ADHD'], 'May cause digestive upset. Avoid during pregnancy.', 'Brain tonic used in Ayurveda for memory and cognitive enhancement.', ARRAY['brahmi', 'bacopa', 'water hyssop']),
('Peppermint', 'Mentha piperita', 'Herb', ARRAY['Leaves', 'Oil'], ARRAY['Digestive aid', 'Anti-spasmodic', 'Analgesic', 'Antimicrobial'], ARRAY['IBS', 'Headaches', 'Digestive issues', 'Respiratory relief'], 'May worsen acid reflux. Avoid oil in infants.', 'Cooling herb with digestive and pain-relieving properties.', ARRAY['peppermint', 'mentha', 'mint']),
('Chamomile', 'Matricaria chamomilla', 'Herb', ARRAY['Flowers'], ARRAY['Anti-inflammatory', 'Sedative', 'Anti-anxiety', 'Digestive aid'], ARRAY['Insomnia', 'Anxiety', 'Digestive issues', 'Skin inflammation'], 'May cause allergic reactions in those sensitive to ragweed.', 'Gentle flower used for relaxation and digestive comfort.', ARRAY['chamomile', 'matricaria', 'camomile']),
('Lavender', 'Lavandula angustifolia', 'Herb', ARRAY['Flowers', 'Oil'], ARRAY['Sedative', 'Anti-anxiety', 'Antimicrobial', 'Anti-inflammatory'], ARRAY['Anxiety', 'Insomnia', 'Headaches', 'Skin issues'], 'Generally safe. May cause drowsiness.', 'Aromatic herb known for calming and sleep-promoting effects.', ARRAY['lavender', 'lavandula', 'purple flowers']),
('Garlic', 'Allium sativum', 'Bulb', ARRAY['Bulb', 'Cloves'], ARRAY['Antimicrobial', 'Cardiovascular', 'Immune support', 'Antioxidant'], ARRAY['High blood pressure', 'High cholesterol', 'Infections', 'Immune boost'], 'May interact with blood thinners. Can cause digestive upset.', 'Pungent bulb with powerful cardiovascular and immune benefits.', ARRAY['garlic', 'allium', 'bulb']),
('Echinacea', 'Echinacea purpurea', 'Herb', ARRAY['Roots', 'Leaves', 'Flowers'], ARRAY['Immunostimulant', 'Anti-inflammatory', 'Antimicrobial'], ARRAY['Cold prevention', 'Upper respiratory infections', 'Wound healing'], 'Not for autoimmune conditions. May cause allergic reactions.', 'Purple coneflower used to boost immune function and fight infections.', ARRAY['echinacea', 'coneflower', 'purple']),
('St. Johns Wort', 'Hypericum perforatum', 'Herb', ARRAY['Flowering tops', 'Leaves'], ARRAY['Antidepressant', 'Anti-anxiety', 'Anti-inflammatory', 'Wound healing'], ARRAY['Mild depression', 'Anxiety', 'Nerve pain', 'Wound healing'], 'Many drug interactions. Causes photosensitivity.', 'Yellow-flowered herb used for mood support and nerve pain.', ARRAY['st johns wort', 'hypericum', 'yellow flowers']),
('Valerian', 'Valeriana officinalis', 'Herb', ARRAY['Root'], ARRAY['Sedative', 'Anti-anxiety', 'Muscle relaxant'], ARRAY['Insomnia', 'Anxiety', 'Muscle tension', 'Restlessness'], 'May cause drowsiness. Can interact with sedatives.', 'Root used for sleep support and nervous system calming.', ARRAY['valerian', 'valeriana', 'root']),
('Ginkgo', 'Ginkgo biloba', 'Tree', ARRAY['Leaves'], ARRAY['Neuroprotective', 'Circulatory', 'Antioxidant', 'Memory enhancer'], ARRAY['Cognitive decline', 'Memory issues', 'Circulation', 'Tinnitus'], 'May interact with blood thinners. Can cause headaches.', 'Ancient tree species used for cognitive and circulatory support.', ARRAY['ginkgo', 'ginkgo biloba', 'fan leaves']),
('Milk Thistle', 'Silybum marianum', 'Herb', ARRAY['Seeds'], ARRAY['Hepatoprotective', 'Antioxidant', 'Anti-inflammatory'], ARRAY['Liver protection', 'Liver disease', 'Detoxification', 'Digestive issues'], 'Generally safe. May cause mild laxative effect.', 'Powerful liver protector with active compound silymarin.', ARRAY['milk thistle', 'silybum', 'thistle']),
('Calendula', 'Calendula officinalis', 'Herb', ARRAY['Flowers'], ARRAY['Anti-inflammatory', 'Antimicrobial', 'Wound healing', 'Anti-fungal'], ARRAY['Skin wounds', 'Burns', 'Rashes', 'Inflammation'], 'May cause allergic reactions in those sensitive to Asteraceae family.', 'Bright orange flower used topically for skin healing.', ARRAY['calendula', 'marigold', 'orange flowers']),
('Fenugreek', 'Trigonella foenum-graecum', 'Herb', ARRAY['Seeds', 'Leaves'], ARRAY['Galactagogue', 'Anti-diabetic', 'Anti-inflammatory', 'Digestive aid'], ARRAY['Increase milk production', 'Blood sugar control', 'Digestive issues', 'Cholesterol'], 'May cause gas. Avoid during pregnancy except for labor induction.', 'Seeds used for lactation support and blood sugar regulation.', ARRAY['fenugreek', 'trigonella', 'seeds']),
('Licorice', 'Glycyrrhiza glabra', 'Root', ARRAY['Root'], ARRAY['Anti-inflammatory', 'Demulcent', 'Adrenal support', 'Antimicrobial'], ARRAY['Cough', 'Sore throat', 'Digestive ulcers', 'Adrenal fatigue'], 'Can raise blood pressure. Not for long-term use. Avoid in hypertension.', 'Sweet root used for respiratory and digestive soothing.', ARRAY['licorice', 'glycyrrhiza', 'root']),
('Dandelion', 'Taraxacum officinale', 'Herb', ARRAY['Root', 'Leaves'], ARRAY['Diuretic', 'Hepatoprotective', 'Digestive bitter', 'Anti-inflammatory'], ARRAY['Liver support', 'Digestion', 'Water retention', 'Detoxification'], 'May cause allergic reactions. Can interact with diuretics.', 'Common weed with powerful liver and digestive benefits.', ARRAY['dandelion', 'taraxacum', 'yellow']),
('Ginseng', 'Panax ginseng', 'Root', ARRAY['Root'], ARRAY['Adaptogenic', 'Immunomodulatory', 'Energy enhancing', 'Cognitive support'], ARRAY['Fatigue', 'Stress', 'Immune support', 'Cognitive function'], 'Can cause insomnia. Not for use with stimulants or during pregnancy.', 'Prized Asian root for energy, vitality and longevity.', ARRAY['ginseng', 'panax', 'root']),
('Hawthorn', 'Crataegus spp.', 'Shrub', ARRAY['Berries', 'Flowers', 'Leaves'], ARRAY['Cardiovascular', 'Antioxidant', 'Circulatory'], ARRAY['Heart health', 'High blood pressure', 'Angina', 'Heart failure'], 'Can interact with heart medications. Requires professional guidance.', 'Berries and flowers used for cardiovascular health support.', ARRAY['hawthorn', 'crataegus', 'berries']),
('Elderberry', 'Sambucus nigra', 'Shrub', ARRAY['Berries', 'Flowers'], ARRAY['Antiviral', 'Immune support', 'Anti-inflammatory', 'Diaphoretic'], ARRAY['Cold and flu', 'Immune support', 'Upper respiratory infections'], 'Raw berries are toxic. Only use cooked berries or extracts.', 'Dark berries with powerful immune-boosting properties.', ARRAY['elderberry', 'sambucus', 'berries']),
('Rosemary', 'Rosmarinus officinalis', 'Herb', ARRAY['Leaves', 'Oil'], ARRAY['Cognitive enhancer', 'Antimicrobial', 'Circulatory', 'Antioxidant'], ARRAY['Memory', 'Circulation', 'Hair growth', 'Digestive issues'], 'High doses may cause seizures. Avoid oil internally during pregnancy.', 'Aromatic herb for memory, circulation and culinary use.', ARRAY['rosemary', 'rosmarinus', 'needles']),
('Thyme', 'Thymus vulgaris', 'Herb', ARRAY['Leaves', 'Oil'], ARRAY['Antimicrobial', 'Expectorant', 'Antioxidant', 'Anti-spasmodic'], ARRAY['Respiratory infections', 'Cough', 'Bronchitis', 'Digestive issues'], 'Generally safe. High doses of oil can be toxic.', 'Powerful antimicrobial herb for respiratory health.', ARRAY['thyme', 'thymus', 'small leaves']),
('Sage', 'Salvia officinalis', 'Herb', ARRAY['Leaves'], ARRAY['Antimicrobial', 'Anti-inflammatory', 'Memory enhancer', 'Astringent'], ARRAY['Sore throat', 'Excessive sweating', 'Menopausal symptoms', 'Memory'], 'Not for use during pregnancy. Can interact with diabetes medications.', 'Silvery herb used for cognitive function and hormonal balance.', ARRAY['sage', 'salvia', 'grey leaves']),
('Oregano', 'Origanum vulgare', 'Herb', ARRAY['Leaves', 'Oil'], ARRAY['Antimicrobial', 'Antioxidant', 'Anti-fungal', 'Anti-inflammatory'], ARRAY['Infections', 'Digestive issues', 'Respiratory infections', 'Skin conditions'], 'Oil is very potent. Dilute before topical use.', 'Powerful antimicrobial herb with culinary uses.', ARRAY['oregano', 'origanum', 'herb']),
('Cinnamon', 'Cinnamomum verum', 'Bark', ARRAY['Bark', 'Oil'], ARRAY['Anti-diabetic', 'Antimicrobial', 'Anti-inflammatory', 'Antioxidant'], ARRAY['Blood sugar control', 'Digestive issues', 'Infections', 'Circulation'], 'High doses can be toxic. May interact with diabetes medications.', 'Sweet warming spice for blood sugar and circulation.', ARRAY['cinnamon', 'cinnamomum', 'bark']),
('Black Pepper', 'Piper nigrum', 'Vine', ARRAY['Fruit', 'Seeds'], ARRAY['Digestive aid', 'Bioavailability enhancer', 'Antimicrobial', 'Antioxidant'], ARRAY['Digestive issues', 'Nutrient absorption', 'Respiratory congestion'], 'Generally safe in culinary amounts. High doses may irritate stomach.', 'Common spice that enhances absorption of other nutrients.', ARRAY['black pepper', 'piper', 'peppercorn']),
('Cardamom', 'Elettaria cardamomum', 'Pod', ARRAY['Seeds', 'Pods'], ARRAY['Digestive aid', 'Anti-inflammatory', 'Antimicrobial', 'Respiratory support'], ARRAY['Digestive issues', 'Bad breath', 'Respiratory infections', 'Nausea'], 'Generally safe in culinary amounts.', 'Aromatic spice for digestion and breath freshening.', ARRAY['cardamom', 'elettaria', 'pod']),
('Clove', 'Syzygium aromaticum', 'Flower bud', ARRAY['Flower buds', 'Oil'], ARRAY['Analgesic', 'Antimicrobial', 'Anti-inflammatory', 'Dental health'], ARRAY['Toothache', 'Oral health', 'Digestive issues', 'Pain relief'], 'Oil is very potent. Can irritate mucous membranes.', 'Aromatic bud used for dental pain and antimicrobial properties.', ARRAY['clove', 'syzygium', 'buds']),
('Fennel', 'Foeniculum vulgare', 'Herb', ARRAY['Seeds', 'Bulb', 'Leaves'], ARRAY['Digestive aid', 'Galactagogue', 'Anti-spasmodic', 'Diuretic'], ARRAY['Digestive issues', 'Colic', 'Lactation support', 'Bloating'], 'May have estrogenic effects. Avoid in hormone-sensitive conditions.', 'Anise-flavored seeds for digestive comfort and lactation.', ARRAY['fennel', 'foeniculum', 'seeds']),
('Senna', 'Senna alexandrina', 'Shrub', ARRAY['Leaves', 'Pods'], ARRAY['Laxative', 'Purgative'], ARRAY['Constipation', 'Bowel cleansing'], 'Not for long-term use. Can cause dependence and electrolyte imbalance.', 'Powerful natural laxative for short-term constipation relief.', ARRAY['senna', 'alexandrina', 'leaves']),
('Psyllium', 'Plantago ovata', 'Herb', ARRAY['Seed husks'], ARRAY['Bulk laxative', 'Cholesterol lowering', 'Blood sugar control'], ARRAY['Constipation', 'High cholesterol', 'Blood sugar regulation', 'IBS'], 'Must take with adequate water. May interact with medications.', 'Fiber-rich husks for digestive regularity and cholesterol.', ARRAY['psyllium', 'plantago', 'husks']),
('Slippery Elm', 'Ulmus rubra', 'Tree', ARRAY['Inner bark'], ARRAY['Demulcent', 'Anti-inflammatory', 'Soothing'], ARRAY['Sore throat', 'Digestive inflammation', 'IBS', 'Wounds'], 'Generally safe. May slow absorption of medications.', 'Soothing bark for digestive and throat inflammation.', ARRAY['slippery elm', 'ulmus', 'bark']),
('Marshmallow', 'Althaea officinalis', 'Herb', ARRAY['Root', 'Leaves'], ARRAY['Demulcent', 'Anti-inflammatory', 'Expectorant'], ARRAY['Cough', 'Sore throat', 'Digestive inflammation', 'Dry skin'], 'Generally safe. May slow absorption of medications.', 'Mucilaginous root for soothing irritated tissues.', ARRAY['marshmallow', 'althaea', 'root']),
('Mullein', 'Verbascum thapsus', 'Herb', ARRAY['Leaves', 'Flowers'], ARRAY['Expectorant', 'Demulcent', 'Anti-inflammatory'], ARRAY['Respiratory infections', 'Cough', 'Bronchitis', 'Ear infections'], 'Generally safe. Filter tea to remove tiny hairs.', 'Tall flowering plant for respiratory health.', ARRAY['mullein', 'verbascum', 'leaves']),
('Yarrow', 'Achillea millefolium', 'Herb', ARRAY['Flowers', 'Leaves'], ARRAY['Hemostatic', 'Anti-inflammatory', 'Diaphoretic', 'Digestive bitter'], ARRAY['Wound healing', 'Fever', 'Digestive issues', 'Menstrual cramps'], 'May cause allergic reactions. Avoid during pregnancy.', 'White flowering herb for wound healing and fever.', ARRAY['yarrow', 'achillea', 'white flowers']),
('Witch Hazel', 'Hamamelis virginiana', 'Shrub', ARRAY['Bark', 'Leaves'], ARRAY['Astringent', 'Anti-inflammatory', 'Hemostatic'], ARRAY['Skin inflammation', 'Hemorrhoids', 'Varicose veins', 'Minor wounds'], 'Generally safe for topical use. Not for internal use.', 'Astringent plant for skin conditions and hemorrhoids.', ARRAY['witch hazel', 'hamamelis', 'shrub']),
('Comfrey', 'Symphytum officinale', 'Herb', ARRAY['Leaves', 'Root'], ARRAY['Wound healing', 'Anti-inflammatory', 'Cell proliferant'], ARRAY['Bruises', 'Sprains', 'Wounds', 'Bone healing'], 'ONLY FOR EXTERNAL USE. Internal use can damage liver.', 'Powerful wound healer for external use only.', ARRAY['comfrey', 'symphytum', 'leaves']),
('Arnica', 'Arnica montana', 'Herb', ARRAY['Flowers'], ARRAY['Anti-inflammatory', 'Analgesic', 'Wound healing'], ARRAY['Bruises', 'Muscle pain', 'Sprains', 'Inflammation'], 'ONLY FOR EXTERNAL USE OR HOMEOPATHIC. Toxic if ingested.', 'Yellow flower for topical pain and bruise relief.', ARRAY['arnica', 'montana', 'yellow']),
('Plantain', 'Plantago major', 'Herb', ARRAY['Leaves'], ARRAY['Anti-inflammatory', 'Antimicrobial', 'Astringent', 'Wound healing'], ARRAY['Insect bites', 'Wounds', 'Skin irritation', 'Respiratory issues'], 'Generally safe. Common yard weed with medicinal properties.', 'Common broadleaf plant for first aid and respiratory health.', ARRAY['plantain', 'plantago', 'broadleaf']),
('Red Clover', 'Trifolium pratense', 'Herb', ARRAY['Flowers'], ARRAY['Phytoestrogenic', 'Blood purifier', 'Expectorant'], ARRAY['Menopausal symptoms', 'Skin conditions', 'Respiratory issues', 'Detoxification'], 'Not for hormone-sensitive conditions. May interact with blood thinners.', 'Pink flowering herb for hormonal balance and skin health.', ARRAY['red clover', 'trifolium', 'pink flowers']),
('Nettle', 'Urtica dioica', 'Herb', ARRAY['Leaves', 'Root'], ARRAY['Anti-inflammatory', 'Diuretic', 'Nutritive', 'Anti-allergic'], ARRAY['Allergies', 'Prostate health', 'Joint pain', 'Anemia'], 'Fresh plant stings. Use dried or cooked. May interact with diuretics.', 'Stinging plant rich in nutrients for allergies and inflammation.', ARRAY['nettle', 'urtica', 'stinging']),
('Burdock', 'Arctium lappa', 'Herb', ARRAY['Root', 'Seeds'], ARRAY['Blood purifier', 'Anti-inflammatory', 'Diuretic', 'Prebiotic'], ARRAY['Skin conditions', 'Detoxification', 'Digestive health', 'Blood sugar'], 'Generally safe. May interact with diabetes medications.', 'Root vegetable for detoxification and skin health.', ARRAY['burdock', 'arctium', 'root']),
('Yellow Dock', 'Rumex crispus', 'Herb', ARRAY['Root'], ARRAY['Blood builder', 'Laxative', 'Hepatic', 'Alterative'], ARRAY['Anemia', 'Constipation', 'Skin conditions', 'Liver support'], 'High in oxalic acid. Avoid in kidney stones.', 'Iron-rich root for blood building and skin conditions.', ARRAY['yellow dock', 'rumex', 'dock']),
('Raspberry', 'Rubus idaeus', 'Shrub', ARRAY['Leaves', 'Fruit'], ARRAY['Uterine tonic', 'Astringent', 'Anti-inflammatory', 'Nutritive'], ARRAY['Pregnancy support', 'Menstrual cramps', 'Diarrhea', 'Mouth sores'], 'Generally safe. Traditional pregnancy tonic (consult practitioner).', 'Leaf tea used as pregnancy tonic and for womens health.', ARRAY['raspberry', 'rubus', 'leaves']),
('Blackberry', 'Rubus fruticosus', 'Shrub', ARRAY['Leaves', 'Root', 'Fruit'], ARRAY['Astringent', 'Anti-inflammatory', 'Antioxidant'], ARRAY['Diarrhea', 'Sore throat', 'Mouth inflammation', 'Skin conditions'], 'Generally safe. Traditional remedy for digestive issues.', 'Bramble with astringent leaves for digestive health.', ARRAY['blackberry', 'rubus', 'bramble']),
('Bilberry', 'Vaccinium myrtillus', 'Shrub', ARRAY['Fruit'], ARRAY['Antioxidant', 'Vision support', 'Circulatory', 'Anti-inflammatory'], ARRAY['Eye health', 'Night vision', 'Circulation', 'Diabetes'], 'Generally safe. May interact with blood thinners.', 'European blueberry for vision and circulatory health.', ARRAY['bilberry', 'vaccinium', 'berries']),
('Cranberry', 'Vaccinium macrocarpon', 'Shrub', ARRAY['Fruit'], ARRAY['Urinary antiseptic', 'Antioxidant', 'Anti-adhesion'], ARRAY['UTI prevention', 'Kidney health', 'Urinary tract health'], 'May interact with blood thinners. Not for treating active infections.', 'Tart berry for urinary tract health.', ARRAY['cranberry', 'vaccinium', 'red berries']),
('Blueberry', 'Vaccinium corymbosum', 'Shrub', ARRAY['Fruit', 'Leaves'], ARRAY['Antioxidant', 'Cognitive support', 'Anti-inflammatory', 'Vision support'], ARRAY['Cognitive health', 'Vision', 'Diabetes', 'Circulation'], 'Generally safe. Rich in beneficial compounds.', 'Antioxidant-rich berry for brain and vision health.', ARRAY['blueberry', 'vaccinium', 'blue berries']),
('Gotu Kola', 'Centella asiatica', 'Herb', ARRAY['Leaves', 'Whole plant'], ARRAY['Cognitive enhancer', 'Wound healing', 'Circulatory', 'Nervine'], ARRAY['Memory', 'Wound healing', 'Varicose veins', 'Anxiety'], 'May cause photosensitivity. Not for use during pregnancy.', 'Brain tonic and wound healer from Ayurvedic medicine.', ARRAY['gotu kola', 'centella', 'pennywort']),
('Rhodiola', 'Rhodiola rosea', 'Root', ARRAY['Root'], ARRAY['Adaptogenic', 'Anti-fatigue', 'Cognitive enhancer', 'Mood support'], ARRAY['Stress', 'Fatigue', 'Depression', 'Cognitive performance'], 'Can cause jitteriness in some. Avoid in bipolar disorder.', 'Arctic root for stress resilience and energy.', ARRAY['rhodiola', 'golden root', 'arctic']),
('Schisandra', 'Schisandra chinensis', 'Vine', ARRAY['Berries'], ARRAY['Adaptogenic', 'Hepatoprotective', 'Cognitive enhancer', 'Endurance'], ARRAY['Liver health', 'Stress', 'Athletic performance', 'Mental clarity'], 'Generally safe. May cause mild digestive upset.', 'Five-flavor berry for liver protection and endurance.', ARRAY['schisandra', 'magnolia vine', 'berries']),
('Eleuthero', 'Eleutherococcus senticosus', 'Shrub', ARRAY['Root', 'Bark'], ARRAY['Adaptogenic', 'Immune support', 'Energy enhancing'], ARRAY['Fatigue', 'Stress', 'Athletic performance', 'Immune support'], 'May cause insomnia. Not for use in high blood pressure.', 'Siberian ginseng for energy and stress adaptation.', ARRAY['eleuthero', 'eleutherococcus', 'siberian ginseng']),
('Reishi', 'Ganoderma lucidum', 'Mushroom', ARRAY['Fruiting body'], ARRAY['Immunomodulatory', 'Adaptogenic', 'Hepatoprotective', 'Cardiovascular'], ARRAY['Immune support', 'Stress', 'Sleep', 'Cardiovascular health'], 'May interact with immunosuppressants and blood thinners.', 'Medicinal mushroom for longevity and immune health.', ARRAY['reishi', 'ganoderma', 'mushroom']),
('Shiitake', 'Lentinula edodes', 'Mushroom', ARRAY['Fruiting body'], ARRAY['Immune support', 'Cardiovascular', 'Anti-cancer', 'Antiviral'], ARRAY['Immune function', 'Cholesterol', 'Cancer support', 'Infections'], 'Generally safe. May cause skin rash in some individuals.', 'Culinary and medicinal mushroom for immune health.', ARRAY['shiitake', 'lentinula', 'mushroom']),
('Chaga', 'Inonotus obliquus', 'Mushroom', ARRAY['Sclerotium'], ARRAY['Antioxidant', 'Immune support', 'Anti-inflammatory', 'Anti-cancer'], ARRAY['Immune support', 'Inflammation', 'Cancer support', 'Skin health'], 'May interact with blood thinners. High in oxalates.', 'Potent antioxidant mushroom growing on birch trees.', ARRAY['chaga', 'inonotus', 'black mushroom']),
('Lions Mane', 'Hericium erinaceus', 'Mushroom', ARRAY['Fruiting body'], ARRAY['Neuroprotective', 'Cognitive enhancer', 'Nerve regeneration', 'Digestive support'], ARRAY['Cognitive function', 'Nerve damage', 'Digestive health', 'Anxiety'], 'Generally safe. May cause allergic reactions in some.', 'Unique mushroom for brain health and nerve regeneration.', ARRAY['lions mane', 'hericium', 'white mushroom']),
('Turkey Tail', 'Trametes versicolor', 'Mushroom', ARRAY['Fruiting body'], ARRAY['Immunomodulatory', 'Anti-cancer', 'Antioxidant', 'Prebiotic'], ARRAY['Cancer support', 'Immune function', 'Gut health', 'Infections'], 'Generally safe. Well-researched for cancer support.', 'Colorful mushroom with powerful immune benefits.', ARRAY['turkey tail', 'trametes', 'multicolor mushroom']),
('Cordyceps', 'Cordyceps sinensis', 'Mushroom', ARRAY['Fruiting body'], ARRAY['Energy enhancing', 'Athletic performance', 'Immune support', 'Respiratory'], ARRAY['Fatigue', 'Athletic performance', 'Respiratory health', 'Libido'], 'May cause insomnia. Not for autoimmune conditions.', 'Energizing mushroom for athletic performance and vitality.', ARRAY['cordyceps', 'caterpillar fungus', 'mushroom']),
('Maitake', 'Grifola frondosa', 'Mushroom', ARRAY['Fruiting body'], ARRAY['Immunomodulatory', 'Blood sugar control', 'Anti-cancer', 'Adaptogenic'], ARRAY['Immune support', 'Diabetes', 'Cancer support', 'Blood pressure'], 'May interact with diabetes and blood pressure medications.', 'Dancing mushroom for immune and metabolic health.', ARRAY['maitake', 'grifola', 'hen of the woods']),
('Pau d Arco', 'Tabebuia impetiginosa', 'Tree', ARRAY['Inner bark'], ARRAY['Antimicrobial', 'Anti-fungal', 'Anti-cancer', 'Anti-inflammatory'], ARRAY['Candida', 'Infections', 'Cancer support', 'Immune support'], 'High doses can be toxic. May interact with blood thinners.', 'South American tree bark with powerful antimicrobial properties.', ARRAY['pau darco', 'tabebuia', 'inner bark']),
('Cat s Claw', 'Uncaria tomentosa', 'Vine', ARRAY['Bark', 'Root'], ARRAY['Immunomodulatory', 'Anti-inflammatory', 'Antioxidant', 'Antiviral'], ARRAY['Immune support', 'Arthritis', 'Viral infections', 'Cancer support'], 'Not for autoimmune conditions or organ transplants.', 'Amazonian vine for immune and joint health.', ARRAY['cats claw', 'uncaria', 'vine']),
('Saw Palmetto', 'Serenoa repens', 'Palm', ARRAY['Berries'], ARRAY['Anti-androgenic', 'Prostate support', 'Anti-inflammatory'], ARRAY['BPH', 'Prostate health', 'Hair loss', 'Urinary symptoms'], 'May interact with hormones. Consult before use with hormone-related conditions.', 'Berry for mens prostate and urinary health.', ARRAY['saw palmetto', 'serenoa', 'palm berries']),
('Pygeum', 'Prunus africana', 'Tree', ARRAY['Bark'], ARRAY['Anti-inflammatory', 'Prostate support', 'Urinary'], ARRAY['BPH', 'Prostate health', 'Urinary symptoms'], 'May cause stomach upset. Sustainable sourcing concerns.', 'African tree bark for prostate health.', ARRAY['pygeum', 'prunus africana', 'bark']),
('Dong Quai', 'Angelica sinensis', 'Root', ARRAY['Root'], ARRAY['Blood tonic', 'Hormone balancing', 'Circulatory'], ARRAY['Menstrual issues', 'Menopausal symptoms', 'Anemia', 'Circulation'], 'Photosensitizing. Not for use during pregnancy or with blood thinners.', 'Chinese herb for womens reproductive health.', ARRAY['dong quai', 'angelica', 'female ginseng']),
('Black Cohosh', 'Actaea racemosa', 'Herb', ARRAY['Root', 'Rhizome'], ARRAY['Phytoestrogenic', 'Anti-inflammatory', 'Sedative'], ARRAY['Menopausal symptoms', 'Menstrual cramps', 'Sleep issues'], 'Not for use during pregnancy. Rare liver concerns.', 'Native American herb for womens hormonal health.', ARRAY['black cohosh', 'actaea', 'bugbane']),
('Chaste Tree', 'Vitex agnus-castus', 'Shrub', ARRAY['Berries'], ARRAY['Hormone balancing', 'Prolactin regulating', 'PMS relief'], ARRAY['PMS', 'Irregular periods', 'Fertility', 'Breast pain'], 'May interact with hormones and Parkinsons medications.', 'Berry for womens hormonal balance and fertility.', ARRAY['chaste tree', 'vitex', 'vitex berries']),
('Wild Yam', 'Dioscorea villosa', 'Root', ARRAY['Root'], ARRAY['Anti-spasmodic', 'Anti-inflammatory', 'Hormone precursor'], ARRAY['Menstrual cramps', 'Menopausal symptoms', 'Digestive spasms'], 'Not a direct source of hormones as often claimed.', 'Root used for menstrual and menopausal discomfort.', ARRAY['wild yam', 'dioscorea', 'yam root']),
('Evening Primrose', 'Oenothera biennis', 'Herb', ARRAY['Oil from seeds'], ARRAY['Anti-inflammatory', 'Hormone balancing', 'Skin health'], ARRAY['PMS', 'Eczema', 'Menopausal symptoms', 'Rheumatoid arthritis'], 'May interact with blood thinners. Can cause mild digestive upset.', 'Seed oil rich in GLA for hormonal and skin health.', ARRAY['evening primrose', 'oenothera', 'yellow flowers']),
('Borage', 'Borago officinalis', 'Herb', ARRAY['Oil from seeds', 'Leaves', 'Flowers'], ARRAY['Anti-inflammatory', 'Skin health', 'Adrenal support'], ARRAY['Eczema', 'Rheumatoid arthritis', 'Stress', 'Respiratory issues'], 'Contains pyrrolizidine alkaloids. Use certified PA-free products.', 'Star-flowered herb with GLA-rich oil for inflammation.', ARRAY['borage', 'borago', 'blue star flowers']),
('Blue Vervain', 'Verbena hastata', 'Herb', ARRAY['Aerial parts'], ARRAY['Nervine', 'Anti-spasmodic', 'Diaphoretic', 'Hepatic'], ARRAY['Anxiety', 'Insomnia', 'Tension headaches', 'Fever'], 'Generally safe. Traditional nervine for nervous tension.', 'Purple-flowered herb for nervous system support.', ARRAY['vervain', 'verbena', 'purple spikes']),
('Skullcap', 'Scutellaria lateriflora', 'Herb', ARRAY['Aerial parts'], ARRAY['Nervine', 'Anti-anxiety', 'Anti-spasmodic', 'Sedative'], ARRAY['Anxiety', 'Insomnia', 'Nervous tension', 'Muscle spasms'], 'Quality varies. Ensure proper identification (not germander).', 'Calming herb for anxiety and nervous system support.', ARRAY['skullcap', 'scutellaria', 'blue flowers']),
('Passionflower', 'Passiflora incarnata', 'Vine', ARRAY['Aerial parts', 'Flowers'], ARRAY['Sedative', 'Anti-anxiety', 'Anti-spasmodic'], ARRAY['Anxiety', 'Insomnia', 'Nervous tension', 'Pain'], 'May cause drowsiness. Avoid with sedative medications.', 'Exotic flower for calming anxiety and promoting sleep.', ARRAY['passionflower', 'passiflora', 'intricate flower']),
('Lemon Balm', 'Melissa officinalis', 'Herb', ARRAY['Leaves'], ARRAY['Anti-anxiety', 'Cognitive enhancer', 'Antiviral', 'Digestive'], ARRAY['Anxiety', 'Insomnia', 'Cold sores', 'Digestive upset'], 'Generally safe. Lemony herb with calming properties.', 'Lemony herb for relaxation and cognitive clarity.', ARRAY['lemon balm', 'melissa', 'mint family']),
('Kava', 'Piper methysticum', 'Root', ARRAY['Root'], ARRAY['Anti-anxiety', 'Sedative', 'Muscle relaxant'], ARRAY['Anxiety', 'Insomnia', 'Muscle tension', 'Stress'], 'CAUTION: Potential liver toxicity. Use quality products and avoid with liver issues.', 'Pacific island root for anxiety relief (use cautiously).', ARRAY['kava', 'piper methysticum', 'root']),
('California Poppy', 'Eschscholzia californica', 'Herb', ARRAY['Aerial parts'], ARRAY['Sedative', 'Analgesic', 'Anti-anxiety'], ARRAY['Insomnia', 'Anxiety', 'Pain', 'Nervous tension'], 'Generally safe. Gentle sedative for sleep support.', 'Golden poppy for gentle sleep and pain relief.', ARRAY['california poppy', 'eschscholzia', 'golden poppy']),
('Hops', 'Humulus lupulus', 'Vine', ARRAY['Flowers (strobiles)'], ARRAY['Sedative', 'Anti-anxiety', 'Phytoestrogenic', 'Bitter digestive'], ARRAY['Insomnia', 'Anxiety', 'Digestive issues', 'Menopausal symptoms'], 'May cause drowsiness. Can have mild estrogenic effects.', 'Bitter flowers used in beer and for sleep support.', ARRAY['hops', 'humulus', 'cone flowers']),
('Catnip', 'Nepeta cataria', 'Herb', ARRAY['Leaves', 'Flowers'], ARRAY['Sedative', 'Digestive', 'Diaphoretic', 'Anti-spasmodic'], ARRAY['Insomnia', 'Anxiety', 'Digestive issues', 'Fever'], 'Generally safe. Calming to humans despite exciting cats.', 'Mint family herb calming to humans, exciting to cats.', ARRAY['catnip', 'nepeta', 'mint leaves']),
('Wood Betony', 'Stachys officinalis', 'Herb', ARRAY['Aerial parts'], ARRAY['Nervine', 'Circulatory', 'Astringent'], ARRAY['Tension headaches', 'Anxiety', 'Neuralgia', 'Sinus issues'], 'Generally safe. Traditional European nervine.', 'European herb for headaches and nervous tension.', ARRAY['wood betony', 'stachys', 'purple flowers']),
('Oat Straw', 'Avena sativa', 'Grain', ARRAY['Milky oats', 'Straw'], ARRAY['Nervine', 'Nutritive', 'Demulcent', 'Anti-depressant'], ARRAY['Nervous exhaustion', 'Stress', 'Skin conditions', 'Addiction recovery'], 'Generally safe. Nourishing to nervous system.', 'Nourishing grain for nervous system restoration.', ARRAY['oat', 'avena', 'grain']),
('Motherwort', 'Leonurus cardiaca', 'Herb', ARRAY['Aerial parts'], ARRAY['Cardiac tonic', 'Nervine', 'Uterine tonic', 'Anti-spasmodic'], ARRAY['Heart palpitations', 'Anxiety', 'Menstrual issues', 'Menopausal symptoms'], 'Not for use during pregnancy (despite the name). May affect thyroid.', 'Heart and womens herb for emotional and physical balance.', ARRAY['motherwort', 'leonurus', 'pink flowers']),
('Damiana', 'Turnera diffusa', 'Shrub', ARRAY['Leaves'], ARRAY['Aphrodisiac', 'Nervine', 'Antidepressant', 'Urinary'], ARRAY['Low libido', 'Depression', 'Anxiety', 'Urinary issues'], 'Generally safe. May interact with diabetes medications.', 'Aromatic herb for libido and mood enhancement.', ARRAY['damiana', 'turnera', 'leaves']),
('Fo-Ti', 'Polygonum multiflorum', 'Root', ARRAY['Root'], ARRAY['Tonic', 'Anti-aging', 'Hair health', 'Liver tonic'], ARRAY['Premature aging', 'Hair loss', 'Constipation', 'Fatigue'], 'Can cause liver damage. Use processed form. Monitor liver function.', 'Chinese longevity herb for anti-aging and vitality.', ARRAY['fo ti', 'he shou wu', 'polygonum']),
('Astragalus', 'Astragalus membranaceus', 'Root', ARRAY['Root'], ARRAY['Immunomodulatory', 'Adaptogenic', 'Cardioprotective', 'Antiviral'], ARRAY['Immune support', 'Fatigue', 'Heart health', 'Kidney health'], 'May interact with immunosuppressants. Use cautiously in autoimmune conditions.', 'Chinese root for immune strength and vitality.', ARRAY['astragalus', 'huang qi', 'root']),
('Codonopsis', 'Codonopsis pilosula', 'Root', ARRAY['Root'], ARRAY['Tonic', 'Immune support', 'Adaptogenic', 'Digestive'], ARRAY['Fatigue', 'Immune weakness', 'Digestive issues', 'Energy'], 'Generally safe. Gentle ginseng alternative.', 'Gentle Chinese root tonic similar to ginseng.', ARRAY['codonopsis', 'dang shen', 'poor mans ginseng']),
('Rehmannia', 'Rehmannia glutinosa', 'Root', ARRAY['Root'], ARRAY['Blood tonic', 'Kidney tonic', 'Anti-inflammatory', 'Immune support'], ARRAY['Anemia', 'Kidney health', 'Adrenal fatigue', 'Immune support'], 'May cause digestive upset. Use with caution in dampness conditions.', 'Chinese root for blood building and kidney health.', ARRAY['rehmannia', 'di huang', 'root']),
('Bloodroot', 'Sanguinaria canadensis', 'Herb', ARRAY['Root'], ARRAY['Expectorant', 'Anti-plaque', 'Antimicrobial'], ARRAY['Respiratory infections', 'Dental health', 'Skin lesions'], 'TOXIC IN HIGH DOSES. External use only or very low doses internally under guidance.', 'Potent root requiring professional guidance for internal use.', ARRAY['bloodroot', 'sanguinaria', 'red root']),
('Goldenseal', 'Hydrastis canadensis', 'Root', ARRAY['Root', 'Rhizome'], ARRAY['Antimicrobial', 'Anti-inflammatory', 'Astringent', 'Bitter digestive'], ARRAY['Infections', 'Digestive issues', 'Mucous membrane inflammation'], 'Endangered species - use alternatives. Not for long-term use. Avoid during pregnancy.', 'Potent antimicrobial root (endangered - use alternatives).', ARRAY['goldenseal', 'hydrastis', 'yellow root']),
('Oregon Grape', 'Mahonia aquifolium', 'Shrub', ARRAY['Root', 'Bark'], ARRAY['Antimicrobial', 'Hepatic', 'Alterative', 'Bitter digestive'], ARRAY['Infections', 'Skin conditions', 'Liver support', 'Digestive issues'], 'Not for use during pregnancy. Sustainable goldenseal alternative.', 'Goldenseal alternative with similar antimicrobial properties.', ARRAY['oregon grape', 'mahonia', 'holly leaves']),
('Barberry', 'Berberis vulgaris', 'Shrub', ARRAY['Root', 'Bark', 'Berries'], ARRAY['Antimicrobial', 'Hepatic', 'Digestive bitter', 'Anti-inflammatory'], ARRAY['Infections', 'Liver support', 'Digestive issues', 'Skin conditions'], 'Not for use during pregnancy. Contains berberine like goldenseal.', 'Yellow-rooted shrub with antimicrobial berberine.', ARRAY['barberry', 'berberis', 'red berries']),
('Uva Ursi', 'Arctostaphylos uva-ursi', 'Shrub', ARRAY['Leaves'], ARRAY['Urinary antiseptic', 'Astringent', 'Diuretic'], ARRAY['UTI', 'Urinary tract infections', 'Kidney stones'], 'Not for long-term use. Requires alkaline urine to work. Not for kidney disease.', 'Bearberry leaves for urinary tract infections.', ARRAY['uva ursi', 'bearberry', 'arctostaphylos']),
('Juniper', 'Juniperus communis', 'Shrub', ARRAY['Berries'], ARRAY['Diuretic', 'Antimicrobial', 'Carminative', 'Anti-rheumatic'], ARRAY['Urinary infections', 'Digestive issues', 'Arthritis', 'Water retention'], 'Not for kidney disease or pregnancy. Not for long-term use.', 'Aromatic berries used in gin and for urinary health.', ARRAY['juniper', 'juniperus', 'blue berries']),
('Horsetail', 'Equisetum arvense', 'Fern', ARRAY['Aerial parts'], ARRAY['Diuretic', 'Astringent', 'Tissue regeneration', 'Remineralizing'], ARRAY['Urinary issues', 'Bone health', 'Hair and nail health', 'Wound healing'], 'Depletes thiamine. Not for long-term use. Contraindicated in some conditions.', 'Silica-rich ancient plant for tissue and bone health.', ARRAY['horsetail', 'equisetum', 'prehistoric plant']),
('Chickweed', 'Stellaria media', 'Herb', ARRAY['Aerial parts'], ARRAY['Demulcent', 'Anti-inflammatory', 'Nutritive', 'Vulnerary'], ARRAY['Skin irritation', 'Eczema', 'Weight loss support', 'Eye inflammation'], 'Generally safe. Common edible weed with medicinal properties.', 'Common garden weed for skin soothing and nutrition.', ARRAY['chickweed', 'stellaria', 'small white flowers']),
('Cleavers', 'Galium aparine', 'Herb', ARRAY['Aerial parts'], ARRAY['Lymphatic', 'Diuretic', 'Alterative', 'Anti-inflammatory'], ARRAY['Lymphatic congestion', 'Urinary issues', 'Skin conditions', 'Edema'], 'Generally safe. Sticky plant for lymphatic drainage.', 'Sticky spring tonic for lymphatic and skin health.', ARRAY['cleavers', 'galium', 'sticky weed']),
('Self-Heal', 'Prunella vulgaris', 'Herb', ARRAY['Aerial parts'], ARRAY['Wound healing', 'Antimicrobial', 'Anti-inflammatory', 'Astringent'], ARRAY['Wounds', 'Sore throat', 'Mouth inflammation', 'Herpes'], 'Generally safe. Common lawn plant with healing properties.', 'Purple-flowered lawn herb for wound healing.', ARRAY['self heal', 'prunella', 'heal all']),
('Alfalfa', 'Medicago sativa', 'Legume', ARRAY['Leaves', 'Seeds', 'Sprouts'], ARRAY['Nutritive', 'Remineralizing', 'Estrogen-like', 'Cholesterol lowering'], ARRAY['Nutritional deficiency', 'High cholesterol', 'Menopausal symptoms', 'Alkalizing'], 'May cause lupus flares. Has mild estrogenic activity. Seeds contain toxic compounds.', 'Nutrient-dense fodder plant for remineralization.', ARRAY['alfalfa', 'medicago', 'sprouts']),
('Kelp', 'Laminaria spp.', 'Seaweed', ARRAY['Whole plant'], ARRAY['Thyroid support', 'Nutritive', 'Remineralizing', 'Metabolic support'], ARRAY['Hypothyroidism', 'Mineral deficiency', 'Weight management', 'Detoxification'], 'High in iodine. Not for hyperthyroidism. Monitor thyroid function.', 'Iodine-rich seaweed for thyroid and metabolic health.', ARRAY['kelp', 'laminaria', 'seaweed']),
('Bladderwrack', 'Fucus vesiculosus', 'Seaweed', ARRAY['Whole plant'], ARRAY['Thyroid support', 'Metabolic support', 'Anti-inflammatory'], ARRAY['Hypothyroidism', 'Weight management', 'Inflammation'], 'High in iodine. Monitor thyroid function. Not for hyperthyroidism.', 'Thyroid-supporting seaweed with air bladders.', ARRAY['bladderwrack', 'fucus', 'seaweed']),
('Irish Moss', 'Chondrus crispus', 'Seaweed', ARRAY['Whole plant'], ARRAY['Demulcent', 'Nutritive', 'Expectorant'], ARRAY['Respiratory issues', 'Digestive inflammation', 'Thyroid support'], 'Generally safe. Mucilaginous seaweed for soothing tissues.', 'Gelatinous seaweed for soothing inflamed tissues.', ARRAY['irish moss', 'chondrus', 'sea moss']),
('Spirulina', 'Arthrospira platensis', 'Algae', ARRAY['Whole organism'], ARRAY['Nutritive', 'Protein source', 'Antioxidant', 'Immune support'], ARRAY['Nutritional support', 'Energy', 'Immune function', 'Detoxification'], 'May be contaminated with heavy metals - use quality sources. Can cause reactions in those with autoimmune conditions.', 'Blue-green algae superfood rich in protein and nutrients.', ARRAY['spirulina', 'blue green algae', 'powder']),
('Chlorella', 'Chlorella vulgaris', 'Algae', ARRAY['Whole organism'], ARRAY['Detoxifying', 'Nutritive', 'Immune support', 'Heavy metal chelation'], ARRAY['Detoxification', 'Heavy metal removal', 'Immune support', 'Nutrition'], 'Can cause digestive upset initially. Start with low doses. Break cell walls for better absorption.', 'Green algae for detoxification and nutrition.', ARRAY['chlorella', 'green algae', 'powder']),
('Moringa', 'Moringa oleifera', 'Tree', ARRAY['Leaves', 'Seeds', 'Pods'], ARRAY['Nutritive', 'Anti-inflammatory', 'Antioxidant', 'Antimicrobial'], ARRAY['Malnutrition', 'Inflammation', 'Blood sugar control', 'Lactation support'], 'Very safe. Highly nutritious "miracle tree" from Asia and Africa.', 'Nutrient-dense "miracle tree" with multiple medicinal uses.', ARRAY['moringa', 'drumstick tree', 'leaves']),
('Hibiscus', 'Hibiscus sabdariffa', 'Flower', ARRAY['Flowers', 'Calyces'], ARRAY['Cardiovascular', 'Diuretic', 'Antioxidant', 'Cooling'], ARRAY['High blood pressure', 'High cholesterol', 'Liver health', 'Hydration'], 'May lower blood pressure significantly. Monitor if on BP medications.', 'Tart red flower for cardiovascular and kidney health.', ARRAY['hibiscus', 'red flower', 'roselle']);

-- Create function to update timestamps
CREATE OR REPLACE FUNCTION public.update_medicinal_plants_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_medicinal_plants_updated_at
BEFORE UPDATE ON public.medicinal_plants
FOR EACH ROW
EXECUTE FUNCTION public.update_medicinal_plants_timestamp();